from dataclasses import dataclass
from enum import Enum


""" PROGRAM SETTING PARAMS """
class BIW_POSITION(Enum):
    RH = 521
    LH = 522


class INSPECTION_STATUS(Enum):
    NONE = -1,
    DOCKING = 1,
    MOVING = 2,
    INSPECTING = 3,
    WAITING = 4


class WORK_STATUS(Enum):
    NONE = -1,
    HOME = 1,
    POSITION1 = 2,
    POSITION2 = 3,
    POSITION3 = 4
    COMPLETE = 5


class BODY_TYPE(Enum):
    NONE = -1,
    NE = "A",
    ME = "B"


class HOLE_TYPE(Enum):
    NONE = -1,
    NO_HOLE = "A",
    HOLE = "B"


PROCESS_THREAD_IS_RUNNING = False
PROCESS_THREAD_MANUAL_BY_PASS = False

SPOT_POSITION = BIW_POSITION.LH
SELECTED_BODY_TYPE = BODY_TYPE.NE

SPOT_HOSTNAME = "10.136.148.12"
SPOT_USERNAME = "admin"
SPOT_PASSWORD = "clientadmin123"
SPOT_DOCK_ID  = SPOT_POSITION.value

BATTERY_LOW_THRESHOLD    = 20
BATTERY_ENOUGH_THRESHOLD = 80

BODY_TYPE_DATA_INDEX = 0    # 1st string (ASCII)
SPEC_DATA_INDEX = 15        # 16th string (ASCII)

HOLE_INSPECTION_RESULT = False

CURRENT_WORK_STATUS = WORK_STATUS.NONE
CURRENT_INSPECTION_STATUS = INSPECTION_STATUS.NONE
CURRENT_WORK_COMPLETE_STATUS = False
WORK_COMPLETE_WAIT_USER_COMMAND = False

MODE_USER_CONFIRM = False
MODE_VIP = False

ADMIN_PASSWORD = "3214"
IMAGE_SAVE_PATH = "D:/BIW/DATA/IMAGE"
CONFIG_PATH = "D:/BIW/CONFIG"

SPOT_DATA_PATH = f"D:/BIW/CONFIG/{SELECTED_BODY_TYPE.name}/{SPOT_POSITION.name}"
SPOT_NAVIGATION_MAP = f"{SPOT_DATA_PATH}/navigation_map_{SELECTED_BODY_TYPE.name}_{SPOT_POSITION.name}"
SPOT_DATA_FILE_NAME = f"spot_data_config_{SELECTED_BODY_TYPE.name}_{SPOT_POSITION.name}.json"
SPOT_MASTER_DATA_PATH = f"D:/BIW/SPOT_CONTROL/master_data/master/arm_correction/{SPOT_POSITION.name}"

# SERVER_URL = "opc.tcp://DESKTOP-B9OTIT0:4990/FactoryTalkLinxGateway1"
# SERVER_URL = "opc.tcp://localhost:4840"
# SERVER_URL = "opc.tcp://SPOT-PC-1-RH:4990/FactoryTalkLinx"
SERVER_URL = "opc.tcp://192.168.1.83:4990/FactoryTalkLinx"  #
SERVER_NAME = "[MF]"


class OPC_AGV_I_TAG:
    S600_AGV_I_AUTORUNNING          = f"{SERVER_NAME}S600_AGV_I_AUTORUNNING"
    S600_AGV_I_BODYTYPE_NONE        = f"{SERVER_NAME}S600_AGV_I_BODYTYPE_NONE"
    S600_AGV_I_BODYTYPE_ON          = f"{SERVER_NAME}S600_AGV_I_BODYTYPE_ON"
    S600_AGV_I_EM_STOP              = f"{SERVER_NAME}S600_AGV_I_EM_STOP"
    S600_AGV_I_FAULT                = f"{SERVER_NAME}S600_AGV_I_FAULT"
    S600_AGV_I_HEART_BIT            = f"{SERVER_NAME}S600_AGV_I_HEART_BIT"
    S600_AGV_I_IN_RUNNING           = f"{SERVER_NAME}S600_AGV_I_IN_RUNNING"
    S600_AGV_I_NON_INT              = f"{SERVER_NAME}S600_AGV_I_NON_INT"
    S600_AGV_I_OUT_RUNNING          = f"{SERVER_NAME}S600_AGV_I_OUT_RUNNING"
    S600_AGV_I_PART_NONE            = f"{SERVER_NAME}S600_AGV_I_PART_NONE"
    S600_AGV_I_PART_OK              = f"{SERVER_NAME}S600_AGV_I_PART_OK"
    S600_AGV_I_POS_OK               = f"{SERVER_NAME}S600_AGV_I_POS_OK"
    S600_AGV_I_WANRNING             = f"{SERVER_NAME}S600_AGV_I_WANRNING"
    S600_AGV_I_Workcompl_Feedback   = f"{SERVER_NAME}S600_AGV_I_Workcompl_Feedback"
    AGV_Position_72180_AGV_NO       = f"{SERVER_NAME}AGV_Position_72180.AGV_No"

class OPC_O_TAG:
    S600_O_Pause = f"{SERVER_NAME}S600_O_Pause"
    S600_O_Reset = f"{SERVER_NAME}S600_O_Reset"


@dataclass
class OPC_SPOT_AGV_BT_Data:
    """S600_SPOT_AGV_BT_Data"""
    S600_SPOT_AGV_BT_Data_Carrier_No    = f"{SERVER_NAME}S600_SPOT_AGV_BT_Data.Carrier.No"
    S600_SPOT_AGV_BT_Data_Carrier_Type  = f"{SERVER_NAME}S600_SPOT_AGV_BT_Data.Carrier.Type"
    S600_SPOT_AGV_BT_Data_SPEC          = f"{SERVER_NAME}S600_SPOT_AGV_BT_Data.SPEC"
    S600_SPOT_AGV_BT_Data_SPEC_LEN      = f"{SERVER_NAME}S600_SPOT_AGV_BT_Data.SPEC.LEN"
    S600_SPOT_AGV_BT_Data_SSN           = f"{SERVER_NAME}S600_SPOT_AGV_BT_Data.SSN"
    S600_SPOT_AGV_BT_Data_SSN_LEN       = f"{SERVER_NAME}S600_SPOT_AGV_BT_Data.SSN.LEN"
    S600_SPOT_AGV_BT_Data_VIN           = f"{SERVER_NAME}S600_SPOT_AGV_BT_Data.VIN"
    S600_SPOT_AGV_BT_Data_VIN_LEN       = f"{SERVER_NAME}S600_SPOT_AGV_BT_Data.VIN.LEN"


class OPC_SPOT_I_RST:
    S600_SPOT_AGV_I_RST = f"{SERVER_NAME}S600_SPOT_AGV_I_RST"
    S600_SPOT_RB_I_RST  = f"{SERVER_NAME}S600_SPOT_RB_I_RST"


class OPC_SPOT_Heart_Bit:
    S600_SPOT_PLC_O_Heart_Bit = f"{SERVER_NAME}S600_SPOT_PLC_O_Heart_Bit"


@dataclass
class OPC_SPOT_RB1_WRITE_DATA:
    S600_SPOT_RB1_I_1ST_WORK_COMP   = f"{SERVER_NAME}S600_SPOT_RB1_I_1ST_WORK_COMP"
    S600_SPOT_RB1_I_2ND_WORK_COMP   = f"{SERVER_NAME}S600_SPOT_RB1_I_2ND_WORK_COMP"
    S600_SPOT_RB1_I_3RD_WORK_COMP   = f"{SERVER_NAME}S600_SPOT_RB1_I_3RD_WORK_COMP"
    S600_SPOT_RB1_I_AUTORUNNING     = f"{SERVER_NAME}S600_SPOT_RB1_I_AUTORUNNING"
    S600_SPOT_RB1_I_BATTERY_LOW     = f"{SERVER_NAME}S600_SPOT_RB1_I_BATTERY_LOW"
    S600_SPOT_RB1_I_BYPASS_ON       = f"{SERVER_NAME}S600_SPOT_RB1_I_BYPASS_ON"
    S600_SPOT_RB1_I_CHK1_ERR        = f"{SERVER_NAME}S600_SPOT_RB1_I_CHK1_ERR"
    S600_SPOT_RB1_I_CHK2_ERR        = f"{SERVER_NAME}S600_SPOT_RB1_I_CHK2_ERR"
    S600_SPOT_RB1_I_CHK3_ERR        = f"{SERVER_NAME}S600_SPOT_RB1_I_CHK3_ERR"
    S600_SPOT_RB1_I_EM_STOP         = f"{SERVER_NAME}S600_SPOT_RB1_I_EM_STOP"
    S600_SPOT_RB1_I_HEART_BIT       = f"{SERVER_NAME}S600_SPOT_RB1_I_HEART_BIT"
    S600_SPOT_RB1_I_HOME_POSI       = f"{SERVER_NAME}S600_SPOT_RB1_I_HOME_POSI"
    S600_SPOT_RB1_I_LAST_WORK_COMP  = f"{SERVER_NAME}S600_SPOT_RB1_I_LAST_WORK_COMP"
    S600_SPOT_RB1_I_NON_INT         = f"{SERVER_NAME}S600_SPOT_RB1_I_NON_INT"
    S600_SPOT_RB1_I_TOTAL_ERR       = f"{SERVER_NAME}S600_SPOT_RB1_I_TOTAL_ERR"
    S600_SPOT_RB1_I_WORK_COMP_RESET = f"{SERVER_NAME}S600_SPOT_RB1_I_WORK_COMP_RESET"


@dataclass
class OPC_SPOT_RB2_WRITE_DATA:
    S600_SPOT_RB2_I_1ST_WORK_COMP   = f"{SERVER_NAME}S600_SPOT_RB2_I_1ST_WORK_COMP"
    S600_SPOT_RB2_I_2ND_WORK_COMP   = f"{SERVER_NAME}S600_SPOT_RB2_I_2ND_WORK_COMP"
    S600_SPOT_RB2_I_3RD_WORK_COMP   = f"{SERVER_NAME}S600_SPOT_RB2_I_3RD_WORK_COMP"
    S600_SPOT_RB2_I_AUTORUNNING     = f"{SERVER_NAME}S600_SPOT_RB2_I_AUTORUNNING"
    S600_SPOT_RB2_I_BATTERY_LOW     = f"{SERVER_NAME}S600_SPOT_RB2_I_BATTERY_LOW"
    S600_SPOT_RB2_I_BYPASS_ON       = f"{SERVER_NAME}S600_SPOT_RB2_I_BYPASS_ON"
    S600_SPOT_RB2_I_CHK1_ERR        = f"{SERVER_NAME}S600_SPOT_RB2_I_CHK1_ERR"
    S600_SPOT_RB2_I_CHK2_ERR        = f"{SERVER_NAME}S600_SPOT_RB2_I_CHK2_ERR"
    S600_SPOT_RB2_I_CHK3_ERR        = f"{SERVER_NAME}S600_SPOT_RB2_I_CHK3_ERR"
    S600_SPOT_RB2_I_EM_STOP         = f"{SERVER_NAME}S600_SPOT_RB2_I_EM_STOP"
    S600_SPOT_RB2_I_HEART_BIT       = f"{SERVER_NAME}S600_SPOT_RB2_I_HEART_BIT"
    S600_SPOT_RB2_I_HOME_POSI       = f"{SERVER_NAME}S600_SPOT_RB2_I_HOME_POSI"
    S600_SPOT_RB2_I_LAST_WORK_COMP  = f"{SERVER_NAME}S600_SPOT_RB2_I_LAST_WORK_COMP"
    S600_SPOT_RB2_I_NON_INT         = f"{SERVER_NAME}S600_SPOT_RB2_I_NON_INT"
    S600_SPOT_RB2_I_TOTAL_ERR       = f"{SERVER_NAME}S600_SPOT_RB2_I_TOTAL_ERR"
    S600_SPOT_RB2_I_WORK_COMP_RESET = f"{SERVER_NAME}S600_SPOT_RB2_I_WORK_COMP_RESET"


class OPC_S600_T_Reset:
    """S600_T_Reset"""
    S600_T_Reset_ACC    = f"{SERVER_NAME}S600_T_Reset.ACC"
    S600_T_Reset_DN     = f"{SERVER_NAME}S600_T_Reset.DN"
    S600_T_Reset_EN     = f"{SERVER_NAME}S600_T_Reset.EN"
    S600_T_Reset_PRE    = f"{SERVER_NAME}S600_T_Reset.PRE"
    S600_T_Reset_TT     = f"{SERVER_NAME}S600_T_Reset.TT"


@dataclass
class OPC_SPOT_AGV_OUT_timer:
    """SPOT_AGV_OUT_timer"""
    SPOT_AGV_OUT_timer_ACC  = f"{SERVER_NAME}SPOT_AGV_OUT_timer.ACC"
    SPOT_AGV_OUT_timer_DN   = f"{SERVER_NAME}SPOT_AGV_OUT_timer.DN"
    SPOT_AGV_OUT_timer_EN   = f"{SERVER_NAME}SPOT_AGV_OUT_timer.EN"
    SPOT_AGV_OUT_timer_PRE  = f"{SERVER_NAME}SPOT_AGV_OUT_timer.PRE"
    SPOT_AGV_OUT_timer_TT   = f"{SERVER_NAME}SPOT_AGV_OUT_timer.TT"


@dataclass
class OPC_SPOT_I_AGV:
    """SPOT_I_AGV"""
    SPOT_I_AGV_0 = f"{SERVER_NAME}SPOT_I_AGV[0]"
    SPOT_I_AGV_1 = f"{SERVER_NAME}SPOT_I_AGV[1]"


@dataclass
class OPC_SPOT_I_RB:
    """SPOT_I_RB"""
    SPOT_I_RB_0 = f"{SERVER_NAME}SPOT_I_RB[0]"
    SPOT_I_RB_2 = f"{SERVER_NAME}SPOT_I_RB[1]"


@dataclass
class OPC_SPOT_TEST_TIMER:
    """SPOT_TEST_TIMER"""
    SPOT_TEST_TIMER_ACC = f"{SERVER_NAME}SPOT_TEST_TIMER.ACC"
    SPOT_TEST_TIMER_DN  = f"{SERVER_NAME}SPOT_TEST_TIMER.DN"
    SPOT_TEST_TIMER_EN  = f"{SERVER_NAME}SPOT_TEST_TIMER.EN"
    SPOT_TEST_TIMER_PRE = f"{SERVER_NAME}SPOT_TEST_TIMER.PRE"
    SPOT_TEST_TIMER_TT  = f"{SERVER_NAME}SPOT_TEST_TIMER.TT"


@dataclass()
class OPC_AGV_STATUS:
    """AGV_I_MF AGV_STATUS CARRIER TYPE"""
    def __init__(self, AGV_NO):
        formatted_agv_no = "{0:02d}".format(int(AGV_NO))
        self.AGV_I_MF_AGV_Status_Carrier_Type = f"{SERVER_NAME}AGV_I_MF.AGV_Status[{formatted_agv_no}].Carrier.Type"
